[package]
name = "posts"
version = "0.1.5"
edition = "2024"
description = "CMS blog with admin interface"
license = "MIT"
repository = "https://github.com/stevedylandev/andromeda"
homepage = "https://github.com/stevedylandev/andromeda"

[dependencies]
axum = { workspace = true, features = ["multipart"] }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rusqlite = { workspace = true }
nanoid = { workspace = true }
rust-embed = { workspace = true }
dotenvy = { workspace = true }
subtle = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
andromeda-auth = { workspace = true }
andromeda-db = { workspace = true, features = ["session"] }
andromeda-darkmatter-css = { workspace = true }
serde_rusqlite = "0.41"
askama = "0.15"
askama_web = { version = "0.15", features = ["axum-0.8"] }
pulldown-cmark = "0.12"
chrono = "0.4"
zip = { workspace = true }
tower-http = { version = "0.6.8", features = ["cors"] }
