import { defineConfig } from 'vocs'

export default defineConfig({
  title: 'Andromeda',
  iconUrl: "https://andromeda.build/icon.png",
  ogImageUrl: "https://andromeda.build/og.png",
  markdown: {
    code: {
      themes: {
        light: "github-dark-high-contrast",
        dark: "github-dark-high-contrast",
      },
    },
  },
  socials: [
    {
      icon: "github",
      link: "https://github.com/stevedylandev/andromeda",
    }
  ],
  sidebar: [
    {
      text: 'Intro',
      items: [
        {
          text: 'Quickstart',
          link: '/quickstart',
        },
        {
          text: 'What is Andromeda',
          link: '/what-is-andromeda',
        },
      ],
    },
    {
      text: 'Apps',
      items: [
        {
          text: 'Feeds',
          link: '/apps/feeds',
        },
        {
          text: 'Jotts',
          link: '/apps/jotts',
        },
        {
          text: 'Sipp',
          link: '/apps/sipp',
        },
        {
          text: 'OG',
          link: '/apps/og',
        },
        {
          text: 'Shrink',
          link: '/apps/shrink',
        },
        {
          text: 'Parcels',
          link: '/apps/parcels',
        },
        {
          text: 'Posts',
          link: '/apps/posts',
        },
        {
          text: 'Cellar',
          link: '/apps/cellar',
        },
      ],
    },
    {
      text: 'DIY',
      items: [
        {
          text: 'Stack',
          link: '/diy/stack',
        },
        {
          text: 'Skills',
          link: '/diy/skills',
        },
      ],
    },
  ],
    theme: {
    colorScheme: "dark",
    accentColor: "#ffffff",
    variables: {
      borderRadius: {
        '0': '0px',
        '2': '0px',
        '4': '0px',
        '8': '0px',
      },
      color: {
        white: { light: '#ffffff', dark: '#ffffff' },
        black: { light: '#121113', dark: '#121113' },
        background: { light: '#121113', dark: '#121113' },
        background2: { light: '#121113', dark: '#121113' },
        background3: { light: '#1e1c1f', dark: '#1e1c1f' },
        background4: { light: '#1e1c1f', dark: '#1e1c1f' },
        background5: { light: '#1e1c1f', dark: '#1e1c1f' },
        backgroundAccent: { light: '#ffffff', dark: '#ffffff' },
        backgroundAccentHover: { light: '#ffffff', dark: '#ffffff' },
        backgroundAccentText: { light: '#121113', dark: '#121113' },
        backgroundBlueTint: { light: '#1e1c1f', dark: '#1e1c1f' },
        backgroundDark: { light: '#121113', dark: '#121113' },
        backgroundGreenTint: { light: '#1e1c1f', dark: '#1e1c1f' },
        backgroundGreenTint2: { light: '#1e1c1f', dark: '#1e1c1f' },
        backgroundIrisTint: { light: '#1e1c1f', dark: '#1e1c1f' },
        backgroundRedTint: { light: '#1e1c1f', dark: '#1e1c1f' },
        backgroundRedTint2: { light: '#1e1c1f', dark: '#1e1c1f' },
        backgroundYellowTint: { light: '#1e1c1f', dark: '#1e1c1f' },
        border: { light: '#333', dark: '#333' },
        border2: { light: '#555', dark: '#555' },
        borderAccent: { light: '#ffffff', dark: '#ffffff' },
        borderBlue: { light: '#555', dark: '#555' },
        borderGreen: { light: '#555', dark: '#555' },
        borderIris: { light: '#555', dark: '#555' },
        borderRed: { light: '#555', dark: '#555' },
        borderYellow: { light: '#555', dark: '#555' },
        heading: { light: '#ffffff', dark: '#ffffff' },
        shadow: { light: 'transparent', dark: 'transparent' },
        text: { light: '#ffffff', dark: '#ffffff' },
        text2: { light: 'rgba(255,255,255,0.7)', dark: 'rgba(255,255,255,0.7)' },
        text3: { light: 'rgba(255,255,255,0.5)', dark: 'rgba(255,255,255,0.5)' },
        text4: { light: 'rgba(255,255,255,0.3)', dark: 'rgba(255,255,255,0.3)' },
        textAccent: { light: '#ffffff', dark: '#ffffff' },
        textAccentHover: { light: 'rgba(255,255,255,0.7)', dark: 'rgba(255,255,255,0.7)' },
        textBlue: { light: '#ffffff', dark: '#ffffff' },
        textBlueHover: { light: 'rgba(255,255,255,0.7)', dark: 'rgba(255,255,255,0.7)' },
        textGreen: { light: '#ffffff', dark: '#ffffff' },
        textGreenHover: { light: 'rgba(255,255,255,0.7)', dark: 'rgba(255,255,255,0.7)' },
        textIris: { light: '#ffffff', dark: '#ffffff' },
        textIrisHover: { light: 'rgba(255,255,255,0.7)', dark: 'rgba(255,255,255,0.7)' },
        textRed: { light: '#ffffff', dark: '#ffffff' },
        textRedHover: { light: 'rgba(255,255,255,0.7)', dark: 'rgba(255,255,255,0.7)' },
        textYellow: { light: '#ffffff', dark: '#ffffff' },
        textYellowHover: { light: 'rgba(255,255,255,0.7)', dark: 'rgba(255,255,255,0.7)' },

        blockquoteBorder: { light: '#555', dark: '#555' },
        blockquoteText: { light: 'rgba(255,255,255,0.7)', dark: 'rgba(255,255,255,0.7)' },
        codeBlockBackground: { light: '#1e1c1f', dark: '#1e1c1f' },
        codeCharacterHighlightBackground: { light: '#333', dark: '#333' },
        codeHighlightBackground: { light: '#1e1c1f', dark: '#1e1c1f' },
        codeHighlightBorder: { light: '#333', dark: '#333' },
        codeInlineBackground: { light: '#1e1c1f', dark: '#1e1c1f' },
        codeInlineBorder: { light: '#333', dark: '#333' },
        codeInlineText: { light: '#ffffff', dark: '#ffffff' },
        codeTitleBackground: { light: '#1e1c1f', dark: '#1e1c1f' },
        dangerBackground: { light: '#1e1c1f', dark: '#1e1c1f' },
        dangerBorder: { light: '#ffffff', dark: '#ffffff' },
        dangerText: { light: 'rgba(255,255,255,0.8)', dark: 'rgba(255,255,255,0.8)' },
        dangerTextHover: { light: '#ffffff', dark: '#ffffff' },
        hr: { light: '#333', dark: '#333' },
        infoBackground: { light: '#1e1c1f', dark: '#1e1c1f' },
        infoBorder: { light: '#555', dark: '#555' },
        infoText: { light: 'rgba(255,255,255,0.7)', dark: 'rgba(255,255,255,0.7)' },
        infoTextHover: { light: '#ffffff', dark: '#ffffff' },
        lineNumber: { light: 'rgba(255,255,255,0.3)', dark: 'rgba(255,255,255,0.3)' },
        link: { light: '#ffffff', dark: '#ffffff' },
        linkHover: { light: 'rgba(255,255,255,0.7)', dark: 'rgba(255,255,255,0.7)' },
        noteBackground: { light: '#1e1c1f', dark: '#1e1c1f' },
        noteBorder: { light: '#555', dark: '#555' },
        noteText: { light: 'rgba(255,255,255,0.7)', dark: 'rgba(255,255,255,0.7)' },
        successBackground: { light: '#1e1c1f', dark: '#1e1c1f' },
        successBorder: { light: '#555', dark: '#555' },
        successText: { light: 'rgba(255,255,255,0.7)', dark: 'rgba(255,255,255,0.7)' },
        successTextHover: { light: '#ffffff', dark: '#ffffff' },
        tableBorder: { light: '#333', dark: '#333' },
        tableHeaderBackground: { light: '#1e1c1f', dark: '#1e1c1f' },
        tableHeaderText: { light: 'rgba(255,255,255,0.5)', dark: 'rgba(255,255,255,0.5)' },
        tipBackground: { light: '#1e1c1f', dark: '#1e1c1f' },
        tipBorder: { light: '#555', dark: '#555' },
        tipText: { light: 'rgba(255,255,255,0.7)', dark: 'rgba(255,255,255,0.7)' },
        tipTextHover: { light: '#ffffff', dark: '#ffffff' },
        warningBackground: { light: '#1e1c1f', dark: '#1e1c1f' },
        warningBorder: { light: '#555', dark: '#555' },
        warningText: { light: 'rgba(255,255,255,0.7)', dark: 'rgba(255,255,255,0.7)' },
        warningTextHover: { light: '#ffffff', dark: '#ffffff' },
      },
      content: {
        horizontalPadding: '1rem',
        verticalPadding: '2rem',
        width: '700px',
      },
      fontFamily: {
        default: '"Commit Mono", monospace, sans-serif',
        mono: '"Commit Mono", monospace',
      },
      fontSize: {
        root: '14px',
        h1: '18px',
        h2: '16px',
        h3: '15px',
        h4: '14px',
        h5: '14px',
        h6: '14px',
        code: '13px',
        codeBlock: '13px',
        lineNumber: '12px',
        subtitle: '14px',
        th: '12px',
        td: '14px',
      },
      fontWeight: {
        regular: '400',
        medium: '400',
        semibold: '700',
      },
      lineHeight: {
        code: '1.6',
        heading: '1.4',
        listItem: '1.6',
        outlineItem: '1.6',
        paragraph: '1.6',
      },
    },
  },
})
